[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
note_fi = "EGTLKvCHNE2MEJSSM1iYbZXirc1EjrT471qGJbaBm7jc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/instaastro/Documents/Rust/note-fi/deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
